### ISSUE TITLE
My future with this project

### ISSUE THREAD

**Issue by red031000** [pret/pokediamond#467]
Hey everyone
It's been a while
as I have no way to contact most maintainers directly or mods of the pret server apart from here, I have opted to create an issue, even though this may not be the most appropriate place

with the duration of this project, I have invested a lot of time and effort into it, and I would ideally like to continue doing this, however, as I am not in the pret server anymore, I feel as if I may miss important policy decisions

I guess in the end it's up to the maintainers of this project. I feel as if I have valuable skills and motivation which is desperately needed to continue pokediamond, as very little to no progress has been made since my last merge.

I still maintain that I didn't do what I have been accused of, and I am greatly sorry if my presence upsets or makes people uncomfortable, but I would, if possible, like to continue contributing

please let me know

red031000

**Comment by luigismanslave** [comment]
just like, don't be a pedophile my man

**Comment by SolarisLumos** [comment]
skill issue

**Comment by luigismanslave** [comment]
@RadicalDweamer here's the context https://docs.google.com/document/d/14oZq8Y4RCCQ5qH4_tNus0d7diWh3baEDINbq-35CY7c/

**Comment by luigismanslave** [comment]
@radicaldweamer people saying this is dealt with are liars lmao. they don't wanna lose their little workpony. red0 is a horrible pedophile and this should not be let go.

**Comment by luigismanslave** [comment]
based revo lol

**Comment by luigismanslave** [comment]
gas all pedos inshallah

**Comment by luigismanslave** [comment]
don't forget revo ax6 is also a pedo who believed the age of consent should be 12 lol

**Comment by luigismanslave** [comment]
@lunos red0 controlled frosty monetarily and emotionally- it was grooming of a child. society makes rules to protect people who can't protect themselves (like red0's victims)

**Comment by luigismanslave** [comment]
sneed.

**Comment by LOuroboros** [comment]
> 
> 
> @Lunos red0 controlled frosty monetarily and emotionally- it was grooming of a child. society makes rules to protect people who can't protect themselves (like red0's victims)

You just pinged someone else because my nickname is not "Lunos" on GitHub, lol.

Anyway, I keep hearing all these accusations, but I still never heard Frosted's side of the story, so I refuse to both, believe in anything said or comment on it, until I get to hear it.
Mind you, I'm in no rush and I surely as hell won't try to contact Frosted for this matter.

The decision of letting Red stay or not doesn't depend on me anyway.
It solely depends *(at least in my personal opinion)* on the people who do submit and review PRs for Pokediamond.
Revo made their stance clear, Pikalax washed their hands. I believe Tgsm from the Discord server should have the defining vote.

**Comment by luigismanslave** [comment]
>ive never heard frosted's side of the story but i won't look into it
ok pedo man
>i dont like society telling people they can't be pedophiles
:sus:

**Comment by Laureleen** [comment]
"I won't believe anything until I hear what the person who was groomed has to say". Yeah, because their version of events is going to be accurate. There is literally proof in the document posted above.

**Comment by luigismanslave** [comment]
ty based lauren

**Comment by luigismanslave** [comment]
reposit my dick in your ass lol @LOuroboros

**Comment by LOuroboros** [comment]
> 
> 
> "I won't believe anything until I hear what the person who was groomed has to say". Yeah, because their version of events is going to be accurate. There is literally proof in the document posted above.

You say they were groomed, I say I rather hear how Frosted's own experience was, how they felt about it and whether they themself think they were groomed by Red or not, rather than blindly trust in the words of group that stormed Pret some months back.

It's only fair to listen to all the sides involved in a matter like this.

**Comment by luigismanslave** [comment]
frosted is a mentally ill child who has all his money controlled by someone far older than them. if that isn't immediately weird to you, you might wanna start deleting your social media because someone is gonna find out who you've been grooming.

> stormed pret

lol it was literally one lone shitposter

**Comment by LOuroboros** [comment]
> 
> 
> frosted is a mentally ill child who has all his money controlled by someone far older than them. if that isn't immediately weird to you, you might wanna start deleting your social media because someone is gonna find out who you've been grooming.
> 
> > stormed pret
> 
> lol it was literally one lone shitposter

Who hurt you that made you act like a clown on the internet like this, trying to verbally abuse other people simply because they refuse to take a stance without hearing a story in its entirety?

Calm down, walk away from your computer, take a deep breath and reconsider your behavior.

**Comment by luigismanslave** [comment]
im not a sockpuppet ketsuban you fucking moron, i just hate pedophiles

**Comment by luigismanslave** [comment]
@LOuroboros hate pedos, hate pedo defenders simple as. don't defend pedos or have weird stances on the age of consent like "society is holding me back from molesting 13 year olds" lol

**Comment by luigismanslave** [comment]
reconsider this dick lmao

**Comment by luigismanslave** [comment]
"Am I the only one who's tired of feeding myself day after day? It's such a chore. Soylent depresses me, but I get it..."
-louroboros
:soypog:

**Comment by luigismanslave** [comment]
pidgey weren't you defending red last time, pretty sussy my man. mind if i scan your harddrive. we have reason to believe...

**Comment by LOuroboros** [comment]
> 
> 
> @LOuroboros hate pedos, hate pedo defenders simple as. don't defend pedos or have weird stances on the age of consent like "society is holding me back from molesting 13 year olds" lol

You're making up this entire argument of me being a pedo in your head just because I'm not blindly agreeing with you and would prefer to know the full story before taking a stance, rather than a chunk of it. A chunk that, for all I know, may be bullshit you keep trying to push hard.

I am not a pedophile, I am not attracted by minors. I simply don't agree with accusing Red of pedophilia without hearing the entirety of the story. I heard their side, and the side of all the people who stormed Pret *(it was certainly more than 1 btw)*, and I've yet to hear Frosted's, the person who alongside Red was directly involved in the relationship.

I won't accuse someone of something as serious as pedophilia while missing such an important part of the puzzle. 

Please calm down, try to behave. I did not disrespect you at any moment, you don't need to make up bullshit, or act as childish as you are acting now.
If you insist on acting like this, I'll just end up blocking you.

**Comment by luigismanslave** [comment]
i saw what you were saying my man "i dont think society should keep people (one of them a child) apart if they're in love. go chug your soylent and molest kids elsewhere lou.

**Comment by luigismanslave** [comment]
revo based. pidgey cringe pedophile. muhammad was a pedophile. inshallah.

**Comment by LOuroboros** [comment]
> 
> 
> i saw what you were saying my man "i dont think society should keep people (one of them a child) apart if they're in love. go chug your soylent and molest kids elsewhere lou.

Clearly, you didn't.

> I don't like the idea of society having a say in the lives of people who can think for themself and know what is or what is not good for them, but I agree it is a fair argument.

Those were my exact words. Yes, I think that society should not have a say in the lives of people who can think for themself.
That is my personal opinion about romantic relationships. In a relationship, the parts that conform it are the only ones who should sort out their own feelings towards the other person.

As far as I know, both, Red and Frosted can think for themselves.
I think I already implied it, but I don't know Frosted though, so I can't say for sure if they're an individual who can think for themself.
That, and not knowing their side of this story are the reasons why I prefer not to take a stance, at least not yet.

The last part, "but I agree it is a fair argument", was in agreement to @ProjectRevoTPP's own words; "society has standards".
Which I certainly agree with.

**Comment by luigismanslave** [comment]
frosted was a mentally ill 15 year old and red was 20 lol it doesnt matter what frosted felt or didnt feel because they were manipulated and controlled by someone with power over them

**Comment by PikalaxALT** [comment]
This is devolving into a mudslinging thread. I'm closing this issue. The original request is denied.

**Comment by luigismanslave** [comment]
close these nuts
